package yahoo_auction_crawl_setting_exclude_conditions

type IYahooAuctionCrawlSettingExcludeConditionService interface {
	IFindYahooAuctionCrawlSettingExcludeConditionService
	ICreateYahooAuctionCrawlSettingExcludeConditionService
	IUpdateYahooAuctionCrawlSettingExcludeConditionService
	IDeleteYahooAuctionCrawlSettingExcludeConditionService
}

type YahooAuctionCrawlSettingExcludeConditionService struct {
	*FindYahooAuctionCrawlSettingExcludeConditionService
	*CreateYahooAuctionCrawlSettingExcludeConditionService
	*UpdateYahooAuctionCrawlSettingExcludeConditionService
	*DeleteYahooAuctionCrawlSettingExcludeConditionService
}
