FROM golang:1.21.3

RUN apt-get update && apt-get install -y \
  less \
  vim \
  curl \
  sudo

WORKDIR /app

RUN go install github.com/99designs/gqlgen@v0.17.40

# application
COPY . .

CMD ["go", "run", "server.go"]
