source "https://rubygems.org"

ruby "3.2.2"

gem "bootsnap", require: false
gem "importmap-rails"
gem "jbuilder"
gem "mysql2", "~> 0.5"
gem "playwright-ruby-client", require: "playwright"
gem "puma", ">= 5.0"
gem "rack-cors"
gem "rails", "~> 7.1.1"
gem "redis-namespace"
gem "sidekiq"
gem "sinatra", require: false
gem "sprockets-rails"
gem "stimulus-rails"
gem "turbo-rails"
gem "tzinfo-data", platforms: %i[windows jruby]

group :development, :test do
  gem "debug", platforms: %i[mri windows]
  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rails"
  gem "rspec"
  gem "rspec-queue"
  gem "rspec-rails"
  gem "rubocop"
  gem "rubocop-performance"
  gem "rubocop-rails"
  gem "rubocop-rspec"
end

group :development do
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "factory_bot_rails"
  gem "selenium-webdriver"
end
