package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"

	"github.com/kuroweb/price-monitoring/volumes/bff/graph/model"
	"github.com/kuroweb/price-monitoring/volumes/bff/internal"
)

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.CreateProductInput) (model.CreateProductResult, error) {
	return r.ProductService.CreateProduct(ctx, input)
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, id string, input model.UpdateProductInput) (model.UpdateProductResult, error) {
	return r.ProductService.UpdateProduct(ctx, id, input)
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationResolver) DeleteProduct(ctx context.Context, id string) (model.DeleteProductResult, error) {
	return r.ProductService.DeleteProductById(ctx, id)
}

// CreateYahooAuctionCrawlSettingExcludeKeyword is the resolver for the createYahooAuctionCrawlSettingExcludeKeyword field.
func (r *mutationResolver) CreateYahooAuctionCrawlSettingExcludeKeyword(ctx context.Context, input model.CreateYahooAuctionCrawlSettingExcludeKeywordInput) (model.CreateYahooAuctionCrawlSettingExcludeKeywordResult, error) {
	return r.ProductService.CreateYahooAuctionCrawlSettingExcludeKeyword(ctx, input)
}

// UpdateYahooAuctionCrawlSettingExcludeKeyword is the resolver for the updateYahooAuctionCrawlSettingExcludeKeyword field.
func (r *mutationResolver) UpdateYahooAuctionCrawlSettingExcludeKeyword(ctx context.Context, input model.UpdateYahooAuctionCrawlSettingExcludeKeywordInput) (model.UpdateYahooAuctionCrawlSettingExcludeKeywordResult, error) {
	return r.ProductService.UpdateYahooAuctionCrawlSettingExcludeKeyword(ctx, input)
}

// DeleteYahooAuctionCrawlSettingExcludeKeyword is the resolver for the DeleteYahooAuctionCrawlSettingExcludeKeyword field.
func (r *mutationResolver) DeleteYahooAuctionCrawlSettingExcludeKeyword(ctx context.Context, id string, productID string) (model.DeleteYahooAuctionCrawlSettingExcludeKeywordResult, error) {
	return r.ProductService.DeleteYahooAuctionCrawlSettingExcludeKeyword(ctx, id, productID)
}

// CreateYahooAuctionCrawlSettingExcludeProduct is the resolver for the createYahooAuctionCrawlSettingExcludeProduct field.
func (r *mutationResolver) CreateYahooAuctionCrawlSettingExcludeProduct(ctx context.Context, input model.CreateYahooAuctionCrawlSettingExcludeProductInput) (model.CreateYahooAuctionCrawlSettingExcludeProductResult, error) {
	return r.ProductService.CreateYahooAuctionCrawlSettingExcludeProduct(ctx, input)
}

// UpdateYahooAuctionCrawlSettingExcludeProduct is the resolver for the updateYahooAuctionCrawlSettingExcludeProduct field.
func (r *mutationResolver) UpdateYahooAuctionCrawlSettingExcludeProduct(ctx context.Context, input model.UpdateYahooAuctionCrawlSettingExcludeProductInput) (model.UpdateYahooAuctionCrawlSettingExcludeProductResult, error) {
	return r.ProductService.UpdateYahooAuctionCrawlSettingExcludeProduct(ctx, input)
}

// DeleteYahooAuctionCrawlSettingExcludeProduct is the resolver for the deleteYahooAuctionCrawlSettingExcludeProduct field.
func (r *mutationResolver) DeleteYahooAuctionCrawlSettingExcludeProduct(ctx context.Context, id string, productID string) (model.DeleteYahooAuctionCrawlSettingExcludeProductResult, error) {
	return r.ProductService.DeleteYahooAuctionCrawlSettingExcludeProduct(ctx, id, productID)
}

// CreateYahooAuctionCrawlSettingRequiredKeyword is the resolver for the createYahooAuctionCrawlSettingRequiredKeyword field.
func (r *mutationResolver) CreateYahooAuctionCrawlSettingRequiredKeyword(ctx context.Context, input model.CreateYahooAuctionCrawlSettingRequiredKeywordInput) (model.CreateYahooAuctionCrawlSettingRequiredKeywordResult, error) {
	return r.ProductService.CreateYahooAuctionCrawlSettingRequiredKeyword(ctx, input)
}

// UpdateYahooAuctionCrawlSettingRequiredKeyword is the resolver for the updateYahooAuctionCrawlSettingRequiredKeyword field.
func (r *mutationResolver) UpdateYahooAuctionCrawlSettingRequiredKeyword(ctx context.Context, input model.UpdateYahooAuctionCrawlSettingRequiredKeywordInput) (model.UpdateYahooAuctionCrawlSettingRequiredKeywordResult, error) {
	return r.ProductService.UpdateYahooAuctionCrawlSettingRequiredKeyword(ctx, input)
}

// DeleteYahooAuctionCrawlSettingRequiredKeyword is the resolver for the deleteYahooAuctionCrawlSettingRequiredKeyword field.
func (r *mutationResolver) DeleteYahooAuctionCrawlSettingRequiredKeyword(ctx context.Context, id string, productID string) (model.DeleteYahooAuctionCrawlSettingRequiredKeywordResult, error) {
	return r.ProductService.DeleteYahooAuctionCrawlSettingRequiredKeyword(ctx, id, productID)
}

// CreateMercariCrawlSettingExcludeKeyword is the resolver for the createMercariCrawlSettingExcludeKeyword field.
func (r *mutationResolver) CreateMercariCrawlSettingExcludeKeyword(ctx context.Context, input model.CreateMercariCrawlSettingExcludeKeywordInput) (model.CreateMercariCrawlSettingExcludeKeywordResult, error) {
	return r.ProductService.CreateMercariCrawlSettingExcludeKeyword(ctx, input)
}

// UpdateMercariCrawlSettingExcludeKeyword is the resolver for the updateMercariCrawlSettingExcludeKeyword field.
func (r *mutationResolver) UpdateMercariCrawlSettingExcludeKeyword(ctx context.Context, input model.UpdateMercariCrawlSettingExcludeKeywordInput) (model.UpdateMercariCrawlSettingExcludeKeywordResult, error) {
	return r.ProductService.UpdateMercariCrawlSettingExcludeKeyword(ctx, input)
}

// DeleteMercariCrawlSettingExcludeKeyword is the resolver for the deleteMercariCrawlSettingExcludeKeyword field.
func (r *mutationResolver) DeleteMercariCrawlSettingExcludeKeyword(ctx context.Context, id string, productID string) (model.DeleteMercariCrawlSettingExcludeKeywordResult, error) {
	return r.ProductService.DeleteMercariCrawlSettingExcludeKeyword(ctx, id, productID)
}

// CreateMercariCrawlSettingExcludeProduct is the resolver for the createMercariCrawlSettingExcludeProduct field.
func (r *mutationResolver) CreateMercariCrawlSettingExcludeProduct(ctx context.Context, input model.CreateMercariCrawlSettingExcludeProductInput) (model.CreateMercariCrawlSettingExcludeProductResult, error) {
	return r.ProductService.CreateMercariCrawlSettingExcludeProduct(ctx, input)
}

// UpdateMercariCrawlSettingExcludeProduct is the resolver for the updateMercariCrawlSettingExcludeProduct field.
func (r *mutationResolver) UpdateMercariCrawlSettingExcludeProduct(ctx context.Context, input model.UpdateMercariCrawlSettingExcludeProductInput) (model.UpdateMercariCrawlSettingExcludeProductResult, error) {
	return r.ProductService.UpdateMercariCrawlSettingExcludeProduct(ctx, input)
}

// DeleteMercariCrawlSettingExcludeProduct is the resolver for the deleteMercariCrawlSettingExcludeProduct field.
func (r *mutationResolver) DeleteMercariCrawlSettingExcludeProduct(ctx context.Context, id string, productID string) (model.DeleteMercariCrawlSettingExcludeProductResult, error) {
	return r.ProductService.DeleteMercariCrawlSettingExcludeProduct(ctx, id, productID)
}

// CreateMercariCrawlSettingRequiredKeyword is the resolver for the createMercariCrawlSettingRequiredKeyword field.
func (r *mutationResolver) CreateMercariCrawlSettingRequiredKeyword(ctx context.Context, input model.CreateMercariCrawlSettingRequiredKeywordInput) (model.CreateMercariCrawlSettingRequiredKeywordResult, error) {
	return r.ProductService.CreateMercariCrawlSettingRequiredKeyword(ctx, input)
}

// UpdateMercariCrawlSettingRequiredKeyword is the resolver for the updateMercariCrawlSettingRequiredKeyword field.
func (r *mutationResolver) UpdateMercariCrawlSettingRequiredKeyword(ctx context.Context, input model.UpdateMercariCrawlSettingRequiredKeywordInput) (model.UpdateMercariCrawlSettingRequiredKeywordResult, error) {
	return r.ProductService.UpdateMercariCrawlSettingRequiredKeyword(ctx, input)
}

// DeleteMercariCrawlSettingRequiredKeyword is the resolver for the deleteMercariCrawlSettingRequiredKeyword field.
func (r *mutationResolver) DeleteMercariCrawlSettingRequiredKeyword(ctx context.Context, id string, productID string) (model.DeleteMercariCrawlSettingRequiredKeywordResult, error) {
	return r.ProductService.DeleteMercariCrawlSettingRequiredKeyword(ctx, id, productID)
}

// CreateJanparaCrawlSettingExcludeKeyword is the resolver for the createJanparaCrawlSettingExcludeKeyword field.
func (r *mutationResolver) CreateJanparaCrawlSettingExcludeKeyword(ctx context.Context, input model.CreateJanparaCrawlSettingExcludeKeywordInput) (model.CreateJanparaCrawlSettingExcludeKeywordResult, error) {
	return r.ProductService.CreateJanparaCrawlSettingExcludeKeyword(ctx, input)
}

// UpdateJanparaCrawlSettingExcludeKeyword is the resolver for the updateJanparaCrawlSettingExcludeKeyword field.
func (r *mutationResolver) UpdateJanparaCrawlSettingExcludeKeyword(ctx context.Context, input model.UpdateJanparaCrawlSettingExcludeKeywordInput) (model.UpdateJanparaCrawlSettingExcludeKeywordResult, error) {
	return r.ProductService.UpdateJanparaCrawlSettingExcludeKeyword(ctx, input)
}

// DeleteJanparaCrawlSettingExcludeKeyword is the resolver for the deleteJanparaCrawlSettingExcludeKeyword field.
func (r *mutationResolver) DeleteJanparaCrawlSettingExcludeKeyword(ctx context.Context, id string, productID string) (model.DeleteJanparaCrawlSettingExcludeKeywordResult, error) {
	return r.ProductService.DeleteJanparaCrawlSettingExcludeKeyword(ctx, id, productID)
}

// CreateJanparaCrawlSettingExcludeProduct is the resolver for the createJanparaCrawlSettingExcludeProduct field.
func (r *mutationResolver) CreateJanparaCrawlSettingExcludeProduct(ctx context.Context, input model.CreateJanparaCrawlSettingExcludeProductInput) (model.CreateJanparaCrawlSettingExcludeProductResult, error) {
	return r.ProductService.CreateJanparaCrawlSettingExcludeProduct(ctx, input)
}

// UpdateJanparaCrawlSettingExcludeProduct is the resolver for the updateJanparaCrawlSettingExcludeProduct field.
func (r *mutationResolver) UpdateJanparaCrawlSettingExcludeProduct(ctx context.Context, input model.UpdateJanparaCrawlSettingExcludeProductInput) (model.UpdateJanparaCrawlSettingExcludeProductResult, error) {
	return r.ProductService.UpdateJanparaCrawlSettingExcludeProduct(ctx, input)
}

// DeleteJanparaCrawlSettingExcludeProduct is the resolver for the deleteJanparaCrawlSettingExcludeProduct field.
func (r *mutationResolver) DeleteJanparaCrawlSettingExcludeProduct(ctx context.Context, id string, productID string) (model.DeleteJanparaCrawlSettingExcludeProductResult, error) {
	return r.ProductService.DeleteJanparaCrawlSettingExcludeProduct(ctx, id, productID)
}

// CreateJanparaCrawlSettingRequiredKeyword is the resolver for the createJanparaCrawlSettingRequiredKeyword field.
func (r *mutationResolver) CreateJanparaCrawlSettingRequiredKeyword(ctx context.Context, input model.CreateJanparaCrawlSettingRequiredKeywordInput) (model.CreateJanparaCrawlSettingRequiredKeywordResult, error) {
	return r.ProductService.CreateJanparaCrawlSettingRequiredKeyword(ctx, input)
}

// UpdateJanparaCrawlSettingRequiredKeyword is the resolver for the updateJanparaCrawlSettingRequiredKeyword field.
func (r *mutationResolver) UpdateJanparaCrawlSettingRequiredKeyword(ctx context.Context, input model.UpdateJanparaCrawlSettingRequiredKeywordInput) (model.UpdateJanparaCrawlSettingRequiredKeywordResult, error) {
	return r.ProductService.UpdateJanparaCrawlSettingRequiredKeyword(ctx, input)
}

// DeleteJanparaCrawlSettingRequiredKeyword is the resolver for the deleteJanparaCrawlSettingRequiredKeyword field.
func (r *mutationResolver) DeleteJanparaCrawlSettingRequiredKeyword(ctx context.Context, id string, productID string) (model.DeleteJanparaCrawlSettingRequiredKeywordResult, error) {
	return r.ProductService.DeleteJanparaCrawlSettingRequiredKeyword(ctx, id, productID)
}

// CreateIosysCrawlSettingExcludeKeyword is the resolver for the createIosysCrawlSettingExcludeKeyword field.
func (r *mutationResolver) CreateIosysCrawlSettingExcludeKeyword(ctx context.Context, input model.CreateIosysCrawlSettingExcludeKeywordInput) (model.CreateIosysCrawlSettingExcludeKeywordResult, error) {
	return r.ProductService.CreateIosysCrawlSettingExcludeKeyword(ctx, input)
}

// UpdateIosysCrawlSettingExcludeKeyword is the resolver for the updateIosysCrawlSettingExcludeKeyword field.
func (r *mutationResolver) UpdateIosysCrawlSettingExcludeKeyword(ctx context.Context, input model.UpdateIosysCrawlSettingExcludeKeywordInput) (model.UpdateIosysCrawlSettingExcludeKeywordResult, error) {
	return r.ProductService.UpdateIosysCrawlSettingExcludeKeyword(ctx, input)
}

// DeleteIosysCrawlSettingExcludeKeyword is the resolver for the deleteIosysCrawlSettingExcludeKeyword field.
func (r *mutationResolver) DeleteIosysCrawlSettingExcludeKeyword(ctx context.Context, id string, productID string) (model.DeleteIosysCrawlSettingExcludeKeywordResult, error) {
	return r.ProductService.DeleteIosysCrawlSettingExcludeKeyword(ctx, id, productID)
}

// CreateIosysCrawlSettingExcludeProduct is the resolver for the createIosysCrawlSettingExcludeProduct field.
func (r *mutationResolver) CreateIosysCrawlSettingExcludeProduct(ctx context.Context, input model.CreateIosysCrawlSettingExcludeProductInput) (model.CreateIosysCrawlSettingExcludeProductResult, error) {
	return r.ProductService.CreateIosysCrawlSettingExcludeProduct(ctx, input)
}

// UpdateIosysCrawlSettingExcludeProduct is the resolver for the updateIosysCrawlSettingExcludeProduct field.
func (r *mutationResolver) UpdateIosysCrawlSettingExcludeProduct(ctx context.Context, input model.UpdateIosysCrawlSettingExcludeProductInput) (model.UpdateIosysCrawlSettingExcludeProductResult, error) {
	return r.ProductService.UpdateIosysCrawlSettingExcludeProduct(ctx, input)
}

// DeleteIosysCrawlSettingExcludeProduct is the resolver for the deleteIosysCrawlSettingExcludeProduct field.
func (r *mutationResolver) DeleteIosysCrawlSettingExcludeProduct(ctx context.Context, id string, productID string) (model.DeleteIosysCrawlSettingExcludeProductResult, error) {
	return r.ProductService.DeleteIosysCrawlSettingExcludeProduct(ctx, id, productID)
}

// CreateIosysCrawlSettingRequiredKeyword is the resolver for the createIosysCrawlSettingRequiredKeyword field.
func (r *mutationResolver) CreateIosysCrawlSettingRequiredKeyword(ctx context.Context, input model.CreateIosysCrawlSettingRequiredKeywordInput) (model.CreateIosysCrawlSettingRequiredKeywordResult, error) {
	return r.ProductService.CreateIosysCrawlSettingRequiredKeyword(ctx, input)
}

// UpdateIosysCrawlSettingRequiredKeyword is the resolver for the updateIosysCrawlSettingRequiredKeyword field.
func (r *mutationResolver) UpdateIosysCrawlSettingRequiredKeyword(ctx context.Context, input model.UpdateIosysCrawlSettingRequiredKeywordInput) (model.UpdateIosysCrawlSettingRequiredKeywordResult, error) {
	return r.ProductService.UpdateIosysCrawlSettingRequiredKeyword(ctx, input)
}

// DeleteIosysCrawlSettingRequiredKeyword is the resolver for the deleteIosysCrawlSettingRequiredKeyword field.
func (r *mutationResolver) DeleteIosysCrawlSettingRequiredKeyword(ctx context.Context, id string, productID string) (model.DeleteIosysCrawlSettingRequiredKeywordResult, error) {
	return r.ProductService.DeleteIosysCrawlSettingRequiredKeyword(ctx, id, productID)
}

// CreatePcKoubouCrawlSettingExcludeKeyword is the resolver for the createPcKoubouCrawlSettingExcludeKeyword field.
func (r *mutationResolver) CreatePcKoubouCrawlSettingExcludeKeyword(ctx context.Context, input model.CreatePcKoubouCrawlSettingExcludeKeywordInput) (model.CreatePcKoubouCrawlSettingExcludeKeywordResult, error) {
	return r.ProductService.CreatePcKoubouCrawlSettingExcludeKeyword(ctx, input)
}

// UpdatePcKoubouCrawlSettingExcludeKeyword is the resolver for the updatePcKoubouCrawlSettingExcludeKeyword field.
func (r *mutationResolver) UpdatePcKoubouCrawlSettingExcludeKeyword(ctx context.Context, input model.UpdatePcKoubouCrawlSettingExcludeKeywordInput) (model.UpdatePcKoubouCrawlSettingExcludeKeywordResult, error) {
	return r.ProductService.UpdatePcKoubouCrawlSettingExcludeKeyword(ctx, input)
}

// DeletePcKoubouCrawlSettingExcludeKeyword is the resolver for the deletePcKoubouCrawlSettingExcludeKeyword field.
func (r *mutationResolver) DeletePcKoubouCrawlSettingExcludeKeyword(ctx context.Context, id string, productID string) (model.DeletePcKoubouCrawlSettingExcludeKeywordResult, error) {
	return r.ProductService.DeletePcKoubouCrawlSettingExcludeKeyword(ctx, id, productID)
}

// CreatePcKoubouCrawlSettingExcludeProduct is the resolver for the createPcKoubouCrawlSettingExcludeProduct field.
func (r *mutationResolver) CreatePcKoubouCrawlSettingExcludeProduct(ctx context.Context, input model.CreatePcKoubouCrawlSettingExcludeProductInput) (model.CreatePcKoubouCrawlSettingExcludeProductResult, error) {
	return r.ProductService.CreatePcKoubouCrawlSettingExcludeProduct(ctx, input)
}

// UpdatePcKoubouCrawlSettingExcludeProduct is the resolver for the updatePcKoubouCrawlSettingExcludeProduct field.
func (r *mutationResolver) UpdatePcKoubouCrawlSettingExcludeProduct(ctx context.Context, input model.UpdatePcKoubouCrawlSettingExcludeProductInput) (model.UpdatePcKoubouCrawlSettingExcludeProductResult, error) {
	return r.ProductService.UpdatePcKoubouCrawlSettingExcludeProduct(ctx, input)
}

// DeletePcKoubouCrawlSettingExcludeProduct is the resolver for the deletePcKoubouCrawlSettingExcludeProduct field.
func (r *mutationResolver) DeletePcKoubouCrawlSettingExcludeProduct(ctx context.Context, id string, productID string) (model.DeletePcKoubouCrawlSettingExcludeProductResult, error) {
	return r.ProductService.DeletePcKoubouCrawlSettingExcludeProduct(ctx, id, productID)
}

// CreatePcKoubouCrawlSettingRequiredKeyword is the resolver for the createPcKoubouCrawlSettingRequiredKeyword field.
func (r *mutationResolver) CreatePcKoubouCrawlSettingRequiredKeyword(ctx context.Context, input model.CreatePcKoubouCrawlSettingRequiredKeywordInput) (model.CreatePcKoubouCrawlSettingRequiredKeywordResult, error) {
	return r.ProductService.CreatePcKoubouCrawlSettingRequiredKeyword(ctx, input)
}

// UpdatePcKoubouCrawlSettingRequiredKeyword is the resolver for the updatePcKoubouCrawlSettingRequiredKeyword field.
func (r *mutationResolver) UpdatePcKoubouCrawlSettingRequiredKeyword(ctx context.Context, input model.UpdatePcKoubouCrawlSettingRequiredKeywordInput) (model.UpdatePcKoubouCrawlSettingRequiredKeywordResult, error) {
	return r.ProductService.UpdatePcKoubouCrawlSettingRequiredKeyword(ctx, input)
}

// DeletePcKoubouCrawlSettingRequiredKeyword is the resolver for the deletePcKoubouCrawlSettingRequiredKeyword field.
func (r *mutationResolver) DeletePcKoubouCrawlSettingRequiredKeyword(ctx context.Context, id string, productID string) (model.DeletePcKoubouCrawlSettingRequiredKeywordResult, error) {
	return r.ProductService.DeletePcKoubouCrawlSettingRequiredKeyword(ctx, id, productID)
}

// Mutation returns internal.MutationResolver implementation.
func (r *Resolver) Mutation() internal.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
