package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"

	"github.com/kuroweb/price-monitoring/volumes/bff/graph/model"
	"github.com/kuroweb/price-monitoring/volumes/bff/internal"
)

// YahooAuctionProducts is the resolver for the yahooAuctionProducts field.
func (r *productResolver) YahooAuctionProducts(ctx context.Context, obj *model.Product, published *bool) ([]*model.YahooAuctionProduct, error) {
	return r.ProductService.FindYahooAuctionProduct(ctx, nil, &obj.ID, nil, nil, nil, published)
}

// YahooAuctionCrawlSetting is the resolver for the yahooAuctionCrawlSetting field.
func (r *productResolver) YahooAuctionCrawlSetting(ctx context.Context, obj *model.Product) (*model.YahooAuctionCrawlSetting, error) {
	return r.ProductService.FindYahooAuctionCrawlSetting(ctx, obj.ID)
}

// CalculateDailyYahooAuctionProducts is the resolver for the calculateDailyYahooAuctionProducts field.
func (r *productResolver) CalculateDailyYahooAuctionProducts(ctx context.Context, obj *model.Product) ([]*model.CalculateDailyYahooAuctionProduct, error) {
	return r.ProductService.FindCalculateDailyYahooAuctionProduct(ctx, obj.ID)
}

// YahooAuctionCrawlSettingExcludeKeywords is the resolver for the yahooAuctionCrawlSettingExcludeKeywords field.
func (r *yahooAuctionCrawlSettingResolver) YahooAuctionCrawlSettingExcludeKeywords(ctx context.Context, obj *model.YahooAuctionCrawlSetting) ([]*model.YahooAuctionCrawlSettingExcludeKeyword, error) {
	return r.ProductService.FindYahooAuctionCrawlSettingExcludeKeyword(ctx, obj.ProductID, obj.ID)
}

// Product returns internal.ProductResolver implementation.
func (r *Resolver) Product() internal.ProductResolver { return &productResolver{r} }

// YahooAuctionCrawlSetting returns internal.YahooAuctionCrawlSettingResolver implementation.
func (r *Resolver) YahooAuctionCrawlSetting() internal.YahooAuctionCrawlSettingResolver {
	return &yahooAuctionCrawlSettingResolver{r}
}

type productResolver struct{ *Resolver }
type yahooAuctionCrawlSettingResolver struct{ *Resolver }
