package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"

	"github.com/kuroweb/price-monitoring/volumes/bff/graph/model"
	"github.com/kuroweb/price-monitoring/volumes/bff/internal"
)

// IosysCrawlSettingExcludeKeywords is the resolver for the iosysCrawlSettingExcludeKeywords field.
func (r *iosysCrawlSettingResolver) IosysCrawlSettingExcludeKeywords(ctx context.Context, obj *model.IosysCrawlSetting) ([]*model.IosysCrawlSettingExcludeKeyword, error) {
	return r.ProductService.FindIosysCrawlSettingExcludeKeyword(ctx, obj.ProductID, obj.ID)
}

// IosysCrawlSettingExcludeProducts is the resolver for the iosysCrawlSettingExcludeProducts field.
func (r *iosysCrawlSettingResolver) IosysCrawlSettingExcludeProducts(ctx context.Context, obj *model.IosysCrawlSetting) ([]*model.IosysCrawlSettingExcludeProduct, error) {
	return r.ProductService.FindIosysCrawlSettingExcludeProduct(ctx, obj.ProductID, obj.ID)
}

// IosysCrawlSettingRequiredKeywords is the resolver for the iosysCrawlSettingRequiredKeywords field.
func (r *iosysCrawlSettingResolver) IosysCrawlSettingRequiredKeywords(ctx context.Context, obj *model.IosysCrawlSetting) ([]*model.IosysCrawlSettingRequiredKeyword, error) {
	return r.ProductService.FindIosysCrawlSettingRequiredKeyword(ctx, obj.ProductID, obj.ID)
}

// JanparaCrawlSettingExcludeKeywords is the resolver for the janparaCrawlSettingExcludeKeywords field.
func (r *janparaCrawlSettingResolver) JanparaCrawlSettingExcludeKeywords(ctx context.Context, obj *model.JanparaCrawlSetting) ([]*model.JanparaCrawlSettingExcludeKeyword, error) {
	return r.ProductService.FindJanparaCrawlSettingExcludeKeyword(ctx, obj.ProductID, obj.ID)
}

// JanparaCrawlSettingExcludeProducts is the resolver for the janparaCrawlSettingExcludeProducts field.
func (r *janparaCrawlSettingResolver) JanparaCrawlSettingExcludeProducts(ctx context.Context, obj *model.JanparaCrawlSetting) ([]*model.JanparaCrawlSettingExcludeProduct, error) {
	return r.ProductService.FindJanparaCrawlSettingExcludeProduct(ctx, obj.ProductID, obj.ID)
}

// JanparaCrawlSettingRequiredKeywords is the resolver for the janparaCrawlSettingRequiredKeywords field.
func (r *janparaCrawlSettingResolver) JanparaCrawlSettingRequiredKeywords(ctx context.Context, obj *model.JanparaCrawlSetting) ([]*model.JanparaCrawlSettingRequiredKeyword, error) {
	return r.ProductService.FindJanparaCrawlSettingRequiredKeyword(ctx, obj.ProductID, obj.ID)
}

// MercariCrawlSettingExcludeKeywords is the resolver for the mercariCrawlSettingExcludeKeywords field.
func (r *mercariCrawlSettingResolver) MercariCrawlSettingExcludeKeywords(ctx context.Context, obj *model.MercariCrawlSetting) ([]*model.MercariCrawlSettingExcludeKeyword, error) {
	return r.ProductService.FindMercariCrawlSettingExcludeKeyword(ctx, obj.ProductID, obj.ID)
}

// MercariCrawlSettingExcludeProducts is the resolver for the mercariCrawlSettingExcludeProducts field.
func (r *mercariCrawlSettingResolver) MercariCrawlSettingExcludeProducts(ctx context.Context, obj *model.MercariCrawlSetting) ([]*model.MercariCrawlSettingExcludeProduct, error) {
	return r.ProductService.FindMercariCrawlSettingExcludeProduct(ctx, obj.ProductID, obj.ID)
}

// MercariCrawlSettingRequiredKeywords is the resolver for the mercariCrawlSettingRequiredKeywords field.
func (r *mercariCrawlSettingResolver) MercariCrawlSettingRequiredKeywords(ctx context.Context, obj *model.MercariCrawlSetting) ([]*model.MercariCrawlSettingRequiredKeyword, error) {
	return r.ProductService.FindMercariCrawlSettingRequiredKeyword(ctx, obj.ProductID, obj.ID)
}

// PcKoubouCrawlSettingExcludeKeywords is the resolver for the pcKoubouCrawlSettingExcludeKeywords field.
func (r *pcKoubouCrawlSettingResolver) PcKoubouCrawlSettingExcludeKeywords(ctx context.Context, obj *model.PcKoubouCrawlSetting) ([]*model.PcKoubouCrawlSettingExcludeKeyword, error) {
	return r.ProductService.FindPcKoubouCrawlSettingExcludeKeyword(ctx, obj.ProductID, obj.ID)
}

// PcKoubouCrawlSettingExcludeProducts is the resolver for the pcKoubouCrawlSettingExcludeProducts field.
func (r *pcKoubouCrawlSettingResolver) PcKoubouCrawlSettingExcludeProducts(ctx context.Context, obj *model.PcKoubouCrawlSetting) ([]*model.PcKoubouCrawlSettingExcludeProduct, error) {
	return r.ProductService.FindPcKoubouCrawlSettingExcludeProduct(ctx, obj.ProductID, obj.ID)
}

// PcKoubouCrawlSettingRequiredKeywords is the resolver for the pcKoubouCrawlSettingRequiredKeywords field.
func (r *pcKoubouCrawlSettingResolver) PcKoubouCrawlSettingRequiredKeywords(ctx context.Context, obj *model.PcKoubouCrawlSetting) ([]*model.PcKoubouCrawlSettingRequiredKeyword, error) {
	return r.ProductService.FindPcKoubouCrawlSettingRequiredKeyword(ctx, obj.ProductID, obj.ID)
}

// RelatedProducts is the resolver for the relatedProducts field.
func (r *productResolver) RelatedProducts(ctx context.Context, obj *model.Product, platformMask string, page *int, per *int, sort *string, order *string) ([]*model.RelatedProduct, error) {
	return r.ProductService.FindRelatedProduct(ctx, &obj.ID, platformMask, page, per, sort, order)
}

// YahooAuctionProducts is the resolver for the yahooAuctionProducts field.
func (r *productResolver) YahooAuctionProducts(ctx context.Context, obj *model.Product, published *bool, sort *string, order *string) ([]*model.YahooAuctionProduct, error) {
	return r.ProductService.FindYahooAuctionProduct(ctx, nil, &obj.ID, nil, nil, nil, published, sort, order)
}

// YahooAuctionCrawlSetting is the resolver for the yahooAuctionCrawlSetting field.
func (r *productResolver) YahooAuctionCrawlSetting(ctx context.Context, obj *model.Product) (*model.YahooAuctionCrawlSetting, error) {
	return r.ProductService.FindYahooAuctionCrawlSetting(ctx, obj.ID)
}

// YahooAuctionDailyPurchaseSummaries is the resolver for the yahooAuctionDailyPurchaseSummaries field.
func (r *productResolver) YahooAuctionDailyPurchaseSummaries(ctx context.Context, obj *model.Product) ([]*model.YahooAuctionDailyPurchaseSummary, error) {
	return r.ProductService.FindYahooAuctionDailyPurchaseSummary(ctx, obj.ID)
}

// YahooFleamarketDailyPurchaseSummaries is the resolver for the yahooFleamarketDailyPurchaseSummaries field.
func (r *productResolver) YahooFleamarketDailyPurchaseSummaries(ctx context.Context, obj *model.Product) ([]*model.YahooFleamarketDailyPurchaseSummary, error) {
	return r.ProductService.FindYahooFleamarketDailyPurchaseSummary(ctx, obj.ID)
}

// MercariProducts is the resolver for the mercariProducts field.
func (r *productResolver) MercariProducts(ctx context.Context, obj *model.Product, published *bool, sort *string, order *string) ([]*model.MercariProduct, error) {
	return r.ProductService.FindMercariProduct(ctx, nil, &obj.ID, nil, nil, nil, published, sort, order)
}

// MercariCrawlSetting is the resolver for the mercariCrawlSetting field.
func (r *productResolver) MercariCrawlSetting(ctx context.Context, obj *model.Product) (*model.MercariCrawlSetting, error) {
	return r.ProductService.FindMercariCrawlSetting(ctx, obj.ID)
}

// MercariDailyPurchaseSummaries is the resolver for the mercariDailyPurchaseSummaries field.
func (r *productResolver) MercariDailyPurchaseSummaries(ctx context.Context, obj *model.Product) ([]*model.MercariDailyPurchaseSummary, error) {
	return r.ProductService.FindMercariDailyPurchaseSummary(ctx, obj.ID)
}

// JanparaCrawlSetting is the resolver for the janparaCrawlSetting field.
func (r *productResolver) JanparaCrawlSetting(ctx context.Context, obj *model.Product) (*model.JanparaCrawlSetting, error) {
	return r.ProductService.FindJanparaCrawlSetting(ctx, obj.ID)
}

// IosysCrawlSetting is the resolver for the iosysCrawlSetting field.
func (r *productResolver) IosysCrawlSetting(ctx context.Context, obj *model.Product) (*model.IosysCrawlSetting, error) {
	return r.ProductService.FindIosysCrawlSetting(ctx, obj.ID)
}

// PcKoubouCrawlSetting is the resolver for the pcKoubouCrawlSetting field.
func (r *productResolver) PcKoubouCrawlSetting(ctx context.Context, obj *model.Product) (*model.PcKoubouCrawlSetting, error) {
	return r.ProductService.FindPcKoubouCrawlSetting(ctx, obj.ID)
}

// UsedSofmapCrawlSetting is the resolver for the usedSofmapCrawlSetting field.
func (r *productResolver) UsedSofmapCrawlSetting(ctx context.Context, obj *model.Product) (*model.UsedSofmapCrawlSetting, error) {
	return r.ProductService.FindUsedSofmapCrawlSetting(ctx, obj.ID)
}

// UsedSofmapCrawlSettingExcludeKeywords is the resolver for the usedSofmapCrawlSettingExcludeKeywords field.
func (r *usedSofmapCrawlSettingResolver) UsedSofmapCrawlSettingExcludeKeywords(ctx context.Context, obj *model.UsedSofmapCrawlSetting) ([]*model.UsedSofmapCrawlSettingExcludeKeyword, error) {
	return r.ProductService.FindUsedSofmapCrawlSettingExcludeKeyword(ctx, obj.ProductID, obj.ID)
}

// UsedSofmapCrawlSettingExcludeProducts is the resolver for the usedSofmapCrawlSettingExcludeProducts field.
func (r *usedSofmapCrawlSettingResolver) UsedSofmapCrawlSettingExcludeProducts(ctx context.Context, obj *model.UsedSofmapCrawlSetting) ([]*model.UsedSofmapCrawlSettingExcludeProduct, error) {
	return r.ProductService.FindUsedSofmapCrawlSettingExcludeProduct(ctx, obj.ProductID, obj.ID)
}

// UsedSofmapCrawlSettingRequiredKeywords is the resolver for the usedSofmapCrawlSettingRequiredKeywords field.
func (r *usedSofmapCrawlSettingResolver) UsedSofmapCrawlSettingRequiredKeywords(ctx context.Context, obj *model.UsedSofmapCrawlSetting) ([]*model.UsedSofmapCrawlSettingRequiredKeyword, error) {
	return r.ProductService.FindUsedSofmapCrawlSettingRequiredKeyword(ctx, obj.ProductID, obj.ID)
}

// YahooAuctionCrawlSettingExcludeKeywords is the resolver for the yahooAuctionCrawlSettingExcludeKeywords field.
func (r *yahooAuctionCrawlSettingResolver) YahooAuctionCrawlSettingExcludeKeywords(ctx context.Context, obj *model.YahooAuctionCrawlSetting) ([]*model.YahooAuctionCrawlSettingExcludeKeyword, error) {
	return r.ProductService.FindYahooAuctionCrawlSettingExcludeKeyword(ctx, obj.ProductID, obj.ID)
}

// YahooAuctionCrawlSettingExcludeProducts is the resolver for the yahooAuctionCrawlSettingExcludeProducts field.
func (r *yahooAuctionCrawlSettingResolver) YahooAuctionCrawlSettingExcludeProducts(ctx context.Context, obj *model.YahooAuctionCrawlSetting) ([]*model.YahooAuctionCrawlSettingExcludeProduct, error) {
	return r.ProductService.FindYahooAuctionCrawlSettingExcludeProduct(ctx, obj.ProductID, obj.ID)
}

// YahooAuctionCrawlSettingRequiredKeywords is the resolver for the yahooAuctionCrawlSettingRequiredKeywords field.
func (r *yahooAuctionCrawlSettingResolver) YahooAuctionCrawlSettingRequiredKeywords(ctx context.Context, obj *model.YahooAuctionCrawlSetting) ([]*model.YahooAuctionCrawlSettingRequiredKeyword, error) {
	return r.ProductService.FindYahooAuctionCrawlSettingRequiredKeyword(ctx, obj.ProductID, obj.ID)
}

// IosysCrawlSetting returns internal.IosysCrawlSettingResolver implementation.
func (r *Resolver) IosysCrawlSetting() internal.IosysCrawlSettingResolver {
	return &iosysCrawlSettingResolver{r}
}

// JanparaCrawlSetting returns internal.JanparaCrawlSettingResolver implementation.
func (r *Resolver) JanparaCrawlSetting() internal.JanparaCrawlSettingResolver {
	return &janparaCrawlSettingResolver{r}
}

// MercariCrawlSetting returns internal.MercariCrawlSettingResolver implementation.
func (r *Resolver) MercariCrawlSetting() internal.MercariCrawlSettingResolver {
	return &mercariCrawlSettingResolver{r}
}

// PcKoubouCrawlSetting returns internal.PcKoubouCrawlSettingResolver implementation.
func (r *Resolver) PcKoubouCrawlSetting() internal.PcKoubouCrawlSettingResolver {
	return &pcKoubouCrawlSettingResolver{r}
}

// Product returns internal.ProductResolver implementation.
func (r *Resolver) Product() internal.ProductResolver { return &productResolver{r} }

// UsedSofmapCrawlSetting returns internal.UsedSofmapCrawlSettingResolver implementation.
func (r *Resolver) UsedSofmapCrawlSetting() internal.UsedSofmapCrawlSettingResolver {
	return &usedSofmapCrawlSettingResolver{r}
}

// YahooAuctionCrawlSetting returns internal.YahooAuctionCrawlSettingResolver implementation.
func (r *Resolver) YahooAuctionCrawlSetting() internal.YahooAuctionCrawlSettingResolver {
	return &yahooAuctionCrawlSettingResolver{r}
}

type iosysCrawlSettingResolver struct{ *Resolver }
type janparaCrawlSettingResolver struct{ *Resolver }
type mercariCrawlSettingResolver struct{ *Resolver }
type pcKoubouCrawlSettingResolver struct{ *Resolver }
type productResolver struct{ *Resolver }
type usedSofmapCrawlSettingResolver struct{ *Resolver }
type yahooAuctionCrawlSettingResolver struct{ *Resolver }
