package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"fmt"

	"github.com/kuroweb/price-monitoring/volumes/bff/graph/model"
	"github.com/kuroweb/price-monitoring/volumes/bff/internal"
)

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id string) (*model.Product, error) {
	return r.Srv.GetProductByID(ctx, id)
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, id *string, name *string) ([]*model.Product, error) {
	return r.Srv.GetProductsByParams(ctx, id, name)
}

// YahooAuctionProduct is the resolver for the yahooAuctionProduct field.
func (r *queryResolver) YahooAuctionProduct(ctx context.Context, id string) (*model.YahooAuctionProduct, error) {
	return r.Srv.GetYahooAuctionProductByID(ctx, id)
}

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id string) (model.Node, error) {
	panic(fmt.Errorf("not implemented: Node - node"))
}

// Query returns internal.QueryResolver implementation.
func (r *Resolver) Query() internal.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
