package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strconv"

	"github.com/kuroweb/price-monitoring/volumes/bff/graph/model"
)

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id int) (*model.User, error) {
	url := fmt.Sprintf("http://backend:3000/api/v1/users/%d", id)

	resp, err := http.Get(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, errors.New("Failed to fetch product data")
	}

	var response struct {
		ID   int    `json:"id"`
		Name string `json:"name"`
	}

	decoder := json.NewDecoder(resp.Body)
	if err := decoder.Decode(&response); err != nil {
		return nil, err
	}

	user := &model.User{
		ID:   strconv.Itoa(response.ID),
		Name: response.Name,
	}

	return user, nil
}

// GetUsers is the resolver for the getUsers field.
func (r *queryResolver) GetUsers(ctx context.Context, id *int, name *string) ([]*model.User, error) {
	params := make(url.Values)

	if id != nil {
		params.Set("user[id]", strconv.Itoa(*id))
	}

	if name != nil {
		params.Set("user[name]", *name)
	}

	url := "http://backend:3000/api/v1/users?" + params.Encode()

	resp, err := http.Get(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}

	var response struct {
		Users []struct {
			ID   int    `json:"id"`
			Name string `json:"name"`
		} `json:"users"`
	}

	if err := json.Unmarshal(body, &response); err != nil {
		return nil, err
	}

	var users []*model.User
	for _, user := range response.Users {
		users = append(users, &model.User{
			ID:   strconv.Itoa(user.ID),
			Name: user.Name,
		})
	}

	return users, nil
}

// GetProduct is the resolver for the getProduct field.
func (r *queryResolver) GetProduct(ctx context.Context, id int) (*model.Product, error) {
	url := fmt.Sprintf("http://backend:3000/api/v1/products/%d", id)

	resp, err := http.Get(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, errors.New("Failed to fetch product data")
	}

	var response struct {
		ID   int    `json:"id"`
		Name string `json:"name"`
	}

	decoder := json.NewDecoder(resp.Body)
	if err := decoder.Decode(&response); err != nil {
		return nil, err
	}

	product := &model.Product{
		ID:   strconv.Itoa(response.ID),
		Name: response.Name,
	}

	return product, nil
}

// GetProducts is the resolver for the getProducts field.
func (r *queryResolver) GetProducts(ctx context.Context, id *int, name *string) ([]*model.Product, error) {
	params := make(url.Values)

	if id != nil {
		params.Set("product[id]", strconv.Itoa(*id))
	}

	if name != nil {
		params.Set("product[name]", *name)
	}

	url := "http://backend:3000/api/v1/products?" + params.Encode()

	resp, err := http.Get(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, errors.New("Failed to fetch product data")
	}

	var response struct {
		Products []struct {
			ID   int    `json:"id"`
			Name string `json:"name"`
		} `json:"products"`
	}

	decoder := json.NewDecoder(resp.Body)
	if err := decoder.Decode(&response); err != nil {
		return nil, err
	}

	products := make([]*model.Product, len(response.Products))
	for i, product := range response.Products {
		products[i] = &model.Product{
			ID:   strconv.Itoa(product.ID),
			Name: product.Name,
		}
	}

	return products, nil
}

// GetYahooAuctionProduct is the resolver for the getYahooAuctionProduct field.
func (r *queryResolver) GetYahooAuctionProduct(ctx context.Context, yahooAuctionID string) (*model.YahooAuctionProduct, error) {
	url := fmt.Sprintf("http://backend:3000/api/v1/products/%s", yahooAuctionID)

	resp, err := http.Get(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, errors.New("Failed to fetch yahoo_auction_product data")
	}

	var response struct {
		ID             int    `json:"id"`
		YahooAuctionId string `json:"yahoo_auction_id"`
		Name           string `json:"name"`
		Price          int    `json:"price"`
		Published      bool   `json:"published"`
	}

	decoder := json.NewDecoder(resp.Body)
	if err := decoder.Decode(&response); err != nil {
		return nil, err
	}

	yahooAuctionProduct := &model.YahooAuctionProduct{
		ID:             response.ID,
		YahooAuctionID: response.YahooAuctionId,
		Name:           response.Name,
		Price:          response.Price,
		Published:      response.Published,
	}

	return yahooAuctionProduct, nil
}

// GetYahooAuctionProducts is the resolver for the getYahooAuctionProducts field.
func (r *queryResolver) GetYahooAuctionProducts(ctx context.Context, id *int, yahooAuctionID *string, name *string, price *int, published *bool) ([]*model.YahooAuctionProduct, error) {
	params := make(url.Values)

	if id != nil {
		params.Set("id", strconv.Itoa(*id))
	}

	if yahooAuctionID != nil {
		params.Set("yahoo_auction_id", *yahooAuctionID)
	}

	if name != nil {
		params.Set("name", *name)
	}

	if price != nil {
		params.Set("price", strconv.Itoa(*price))
	}

	if published != nil {
		params.Set("published", strconv.FormatBool(*published))
	}

	url := "http://backend:3000/api/v1/yahoo_auction_products?" + params.Encode()

	resp, err := http.Get(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, errors.New("Failed to fetch yahoo_auction_product data")
	}

	var response struct {
		YahooAuctionProducts []struct {
			ID             int    `json:"id"`
			YahooAuctionId string `json:"yahoo_auction_id"`
			Name           string `json:"name"`
			Price          int    `json:"price"`
			Published      bool   `json:"published"`
		} `json:"yahoo_auction_products"`
	}

	decoder := json.NewDecoder(resp.Body)
	if err := decoder.Decode(&response); err != nil {
		return nil, err
	}

	yahoo_auction_products := make([]*model.YahooAuctionProduct, len(response.YahooAuctionProducts))
	for i, yahoo_auction_product := range response.YahooAuctionProducts {
		yahoo_auction_products[i] = &model.YahooAuctionProduct{
			ID:             yahoo_auction_product.ID,
			YahooAuctionID: yahoo_auction_product.YahooAuctionId,
			Name:           yahoo_auction_product.Name,
			Price:          yahoo_auction_product.Price,
			Published:      yahoo_auction_product.Published,
		}
	}

	return yahoo_auction_products, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
