// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node interface {
	IsNode()
	GetID() string
}

type Product struct {
	ID                   string                 `json:"id"`
	Name                 string                 `json:"name"`
	YahooAuctionProducts []*YahooAuctionProduct `json:"yahooAuctionProducts"`
}

func (Product) IsNode()            {}
func (this Product) GetID() string { return this.ID }

type YahooAuctionProduct struct {
	ID             string `json:"id"`
	ProductID      int    `json:"productId"`
	YahooAuctionID string `json:"yahooAuctionId"`
	Name           string `json:"name"`
	Price          int    `json:"price"`
	Published      bool   `json:"published"`
}

func (YahooAuctionProduct) IsNode()            {}
func (this YahooAuctionProduct) GetID() string { return this.ID }
