package yahoo_auction_crawl_setting_required_keywords

type IYahooAuctionCrawlSettingRequiredKeywordService interface {
	IFindYahooAuctionCrawlSettingRequiredKeywordService
	ICreateYahooAuctionCrawlSettingRequiredKeywordService
	IUpdateYahooAuctionCrawlSettingRequiredKeywordService
	IDeleteYahooAuctionCrawlSettingRequiredKeywordService
}

type YahooAuctionCrawlSettingRequiredKeywordService struct {
	*FindYahooAuctionCrawlSettingRequiredKeywordService
	*CreateYahooAuctionCrawlSettingRequiredKeywordService
	*UpdateYahooAuctionCrawlSettingRequiredKeywordService
	*DeleteYahooAuctionCrawlSettingRequiredKeywordService
}
