FROM ruby:3.2.2

#===================
# packageセットアップ
#===================
RUN apt-get update && apt-get install -y \
  nodejs \
  npm \
  default-mysql-client \
  less \
  vim \
  curl \
  sudo

RUN npm i -g n && n 20.0.0

#======================
# プロジェクトセットアップ
#======================
WORKDIR /app

# application
COPY . .

# gem
RUN bundle install

EXPOSE 3000
CMD ["./bin/rails", "server", "-e", "production"]
