package mercari_crawl_setting_exclude_keywords

type IMercariCrawlSettingExcludeKeywordService interface {
	IFindMercariCrawlSettingExcludeKeywordService
	ICreateMercariCrawlSettingExcludeKeywordService
	IUpdateMercariCrawlSettingExcludeKeywordService
	IDeleteMercariCrawlSettingExcludeKeywordService
}

type MercariCrawlSettingExcludeKeywordService struct {
	*FindMercariCrawlSettingExcludeKeywordService
	*CreateMercariCrawlSettingExcludeKeywordService
	*UpdateMercariCrawlSettingExcludeKeywordService
	*DeleteMercariCrawlSettingExcludeKeywordService
}
